### ISSUE TITLE
please add ipq806x,kirkwood for fastpatch if possible

### ISSUE THREAD

**Issue by jack338c** [openwrt-stuff/qca#2]
Hi @maz-1 
I find your fastpatch for art71xx is really faster than someone else

I have a netgear r7800 and linkys ea4500,Could you add qca branch for them,that's will be perfect
Please,please if you have some spare time
Good lucky ! my idol

**Comment by maz-1** [comment]
Refer to my commit : https://github.com/openwrt-stuff/qca/commit/d8074062bacb8759739c2bbe107c26dff000e91e
It should be quite easy, just to modify a few build flags.

**Comment by jack338c** [comment]
@maz-1 
I can understand something except following stufs,I have totally no idea to deal with
please help me

SUPPORT_CHIP = ISIS ISISC SHIVA DESS
O2 -fno-pic -pipe -mabi=32 -march=mips32r2 -DMODULE -mlong-calls -DEXPORT_SYMTAB



SUPPORT_CHIP = ISIS ISISC SHIVA
-O2 -fno-pic -pipe -mcpu=464fp -DMODULE -mlongcall -DEXPORT_SYMTAB
